### ISSUE TITLE
[IR: turbine py] Cleanup turbine v1 path in turbine py

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-py#122]
## Metadata

Main task: https://github.com/meroxa/product/issues/492

[Intermediate Representation RFC](https://www.notion.so/meroxa/Turbine-Intermediate-Representation-98ee81e4be5648e2a9794b7cb75c9eae).

[Addendum](https://www.notion.so/meroxa/Addendum-Turbine-Intermediate-Representation-RFC-42649002b5fd41efacdcb93f36b61231)

## Context

Remove code paths that allowed creating artifacts via API calls in turbine.

## Acceptance  

- [ ] Remove non IR codepath https://github.com/meroxa/turbine-py/blob/439ec0797974bdd22a40d16bc08fdc6f957ad055/src/turbine/cli.py#L22-L23
- [ ] Remove meroxa-py dependency

**Comment by jkayh** [comment]
closing this for now until reprioritized linked in this [epic](https://github.com/meroxa/product/issues/690) for tracking.
