### ISSUE TITLE
[ktlo] Remove meroxa-py dependency 

### ISSUE THREAD

**Issue by ericcheatham** [meroxa/turbine-py#130]
Turbine-py no longer depends on the use of meroxa-py now that intermediate representation is the default deploy strategy. Remove the dependency and any modules that depend on it.

**Comment by ericcheatham** [comment]
Ticket moved to stalled as we need pre-IR work flow to continue to work to support existing example applications

**Comment by justmisosoup** [comment]
We need to be confident of the state of IR before merging this.
