### ISSUE TITLE
[ research ] Verify Turbine-py S3 Bucket Templating Compatability

### ISSUE THREAD

**Issue by ericcheatham** [meroxa/turbine-py#161]
The forthcoming notion -> s3 connector should be able to use the kafka key as the name of the file delivered to the s3 bucket. We need to verify that that is possible and, if not, scope the work required to make that possible.

**Comment by samirketema** [comment]
Marking as closed - @ericcheatham's research is complete 🙇 . 

If we want to include this, the best path forward is including the Conduit S3 Destination connector on Platform, or adjusting either the notion conduit connector's metadata / extracting the key in turbine apps.
