### ISSUE TITLE
TurbinePy only supports one destination

### ISSUE THREAD

**Issue by justmisosoup** [meroxa/turbine-py#85]
## Description
TurbinePy data apps only support a single source and single destination. Meaning when `Write` is used more than once in the TurbinePy code, it results in an error.

The expected behaviour ideally would act like TurbineJS, where a TurbineJS data app can support a single source and multiple destinations (with unique collection names).

**Comment by justmisosoup** [comment]
This will be addressed in IR work.

**Comment by neovintage** [comment]
@justmisosoup We don't know when IR will show up. If it takes months, we have demo apps that won't work.

**Comment by neovintage** [comment]
@ericcheatham Does this mean that turbine-py can support any number of destinations?

**Comment by ericcheatham** [comment]
@neovintage Yes! The most recent release of turbine-py adds it. There is also a change log for it too
